services:
  gemini_qa_bot:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # Streamlit default port
    env_file:
      - .env  # Load environment variables from .env file
    volumes:
      - .:/app  # Mount the current directory to /app in the container
    command: streamlit run gemini_qa_bot.py  # Command to run your app
